### ISSUE TITLE
Deduplicate consecutive blank lines or trailing blank lines?

### ISSUE THREAD

**Issue by geoffharcourt** [derekprior/vim-trimmer#1]
Any interest in taking a PR to do this? (I'll work on it as a separate plugin otherwise.)

**Comment by derekprior** [comment]
Yeah, sure! Do you think we'd need a separate file type blacklist? Or one-shot deal? I think a one-shot deal is fine.

And here I was pretty certain I was the only person using this.

**Comment by geoffharcourt** [comment]
False!
https://github.com/geoffharcourt/dotfiles-local/commit/f70e47e277af6d4a406db4e1fce0dff5c7e6f4fb

Let's stick with one blacklist while we can. I had been thinking a second one might be needed because there might be reasons in text files why you'd want trailing lines but not trailing whitespace on lines, but that's not worth building unless there's a compelling known case.
